KOD-32.1: added math operations to StaticWebPageController and change…
barteknat/spring-web-app pull request #20
Opened 2021-09-13 17:49 UTC by barteknat

…d index.html according to it

2021-09-13 18:16 UTC, mps4dev requested changes
Po co ci equals? Czy wynik jest taki jaki chcemy?

2021-09-13 18:30 UTC, barteknat commented
> Po co ci equals? Czy wynik jest taki jaki chcemy?

Tak jest, mogę dać normalny znak "="

2021-09-23 17:31 UTC, mps4dev requested changes

2021-09-23 17:31 UTC, mps4dev commented on src/main/java/com/crud/tasks/controller/StaticWebPageController.java
> +        model.put("calc1", "2 * 2 = ");
zbedne linie 16-18

2021-09-29 15:55 UTC, mps4dev approved these changes
:)

2021-10-05 17:11 UTC, merged